### ISSUE TITLE
Hacktoberfest : Add illustrations (TODO)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#12]
I am opening this issue for someone looking to contribute, as per [Hacktoberfest](https://hacktoberfest.com/) event.

Open a PR including changes to all the below TODO List, and make sure to link the issue to the PR so that I get notified that this contribution is done for Hacktoberfest.

Adding the whole list will definitely prove that the contribution is up to the standards of the Hacktoberfest event. 

- **Comment, if you want me to assign this issue to you**

### Illustration List

- [x] [bzzzt](https://www.ls.graphics/illustrations/bzzzt) 
- [x] [Yeeow](https://www.ls.graphics/illustrations/yeeow)
- [x] [Ciank](https://www.ls.graphics/illustrations/ciank-illustration-kit)
- [x] [Tokyo](https://www.kapustin.co/tokyo)
- [x] [Seoul](https://www.kapustin.co/seoul)
- [x] [Material icons](https://www.pixsellz.io/material-icons-library)
- [x] [Influencer & Content Creator](https://drawkit.com/product/influencer-content-creator-illustrations)
- [x] [Mental Health](https://drawkit.com/product/mental-health-illustrations)
- [x] [Animal & Pets](https://drawkit.com/product/animal-pets-illustrations)
- [x] [Ecology & Environment](https://drawkit.com/product/ecology-environment-illustrations)
- [x] [Love & Dating](https://drawkit.com/product/love-dating-illustrations)
- [x] [Finn Character](https://drawkit.com/product/finn-character-illustrations)
- [x] [Chubbs Character](https://drawkit.com/product/chubbs-character-illustrations)
- [x] [Larry Character](https://drawkit.com/product/larry-character-illustrations)
- [x] [Team Work](https://drawkit.com/product/team-work-illustrations)

**Comment by kera-cudmore** [comment]
Evening @Anmol-Baranwal would love to help out with this issue :)

**Comment by Anmol-Baranwal** [comment]
closed by #20
