### ISSUE TITLE
Hacktoberfest : Add illustrations (TODO)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#13]
I am opening this issue for someone looking to contribute, as per [Hacktoberfest](https://hacktoberfest.com/) event.

Open a PR including changes to all the below TODO List of Resources, and make sure to link the issue to the PR so that I get notified that this contribution is done for Hacktoberfest.

Adding the whole list will definitely prove that the contribution is up to the standards of the Hacktoberfest event. 

- **Comment, if you want me to assign this issue to you**

### Illustration

- [ ] [Huumph](https://www.ls.graphics/illustrations/huumph)
- [x] [Yaay](https://www.ls.graphics/illustrations/yaay)
- [ ] [Hooonk](https://www.ls.graphics/illustrations/hooonk)
- [x] [Flumf](https://www.ls.graphics/illustrations/flumf)
- [ ] [Wham](https://www.ls.graphics/illustrations/wham)
- [ ] [Zaap](https://www.ls.graphics/illustrations/zaap)
- [ ] [Bluurp](https://www.ls.graphics/illustrations/bluurp)
- [ ] [Illustrationz.design](https://illustrationz.design/)
- [ ] [Fathers & Family](https://drawkit.com/product/fathers-family)
- [ ] [Flaarp](https://www.ls.graphics/illustrations/flaarp)
- [ ] [Headz.design](https://headz.design/)
- [ ] [Online Shopping](https://drawkit.com/product/online-shopping-illustrations)
- [ ] [Everyday Life](https://drawkit.com/product/everyday-life)
- [x] [Medical & Health](https://drawkit.com/product/medical-health-illustrations)
- [ ] [Cooking & Food](https://drawkit.com/product/cooking-food)
