### ISSUE TITLE
Hacktoberfest : Add illustrations (TODO)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#14]
I am opening this issue for someone looking to contribute, as per [Hacktoberfest](https://hacktoberfest.com/) event.

Open a PR including changes to all the below TODO List of Resources, and make sure to link the issue to the PR so that I get notified that this contribution is done for Hacktoberfest.

Adding the whole list will definitely prove that the contribution is up to the standards of the Hacktoberfest event. 

- **Comment, if you want me to assign this issue to you**

### Illustration

- [ ] [Work Hard](https://www.kapustin.co/work-hard)
- [ ] [Madrid](https://www.kapustin.co/madrid)
- [ ] [Hands](https://www.kapustin.co/hands)
- [ ] [Holidays](https://www.kapustin.co/holidays)
- [ ] [Fashion](https://drawkit.com/product/fashion-illustrations)
- [ ] [Music](https://drawkit.com/product/music-illustrations)
- [ ] [COVID-19 & Treatment](https://drawkit.com/product/health-wellness-illustrations)
- [ ] [Holiday Season](https://drawkit.com/product/holiday-season-illustrations)
- [ ] [Restaurants & Dining](https://drawkit.com/product/restaurants-dining-illustrations)
- [ ] [Election Illustrations](https://drawkit.com/product/election-illustrations)
- [ ] [Nature & Ecology](https://drawkit.com/product/nature-ecology-illustrations)
- [ ] [Transport](https://drawkit.com/product/free-transport-illustrations)
- [ ] [Education & Online Learning](https://drawkit.com/product/education-free-vector-illustrations)
- [ ] [BLM & Social cause](https://drawkit.com/product/black-lives-matter-social-movements-illustrations)
- [x] [Startups and SaaS Icons](https://drawkit.com/product/startups-and-saas-icons)

**Comment by Harsh97x** [comment]
I'd like to work on this, Please assign me.

**Comment by Harsh97x** [comment]
hey, @Anmol-Baranwal I'm having trouble understanding this. Could you please explain a little more?
>Open a PR including changes to all the below TODO List of Resources, and make sure to link the issue to the PR so that I get notified that this contribution is done for Hacktoberfest.>

**Comment by Anmol-Baranwal** [comment]
You have to do all the tasks i.e. basically, you have to add all the above-listed illustrations in a single pull request.

 As adding a single illustration isn't up to the expectations of Hacktoberfest since it could be done in mere minutes. But adding a whole list will definitely make your contribution worthwhile for Hacktoberfest

For specific details, you can take a look at #20

**Comment by Harsh97x** [comment]
ok, I understood.

**Comment by Anmol-Baranwal** [comment]
@Harsh97x 
May I know, till when are you planning to complete this issue?
