### ISSUE TITLE
Hacktoberfest : Add illustrations (TODO)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#15]
I am opening this issue for someone looking to contribute, as per [Hacktoberfest](https://hacktoberfest.com/) event.

Open a PR including changes to all the below TODO List of Resources, and make sure to link the issue to the PR so that I get notified that this contribution is done for Hacktoberfest.

Adding the whole list will definitely prove that the contribution is up to the standards of the Hacktoberfest event. 

- **Comment, if you want me to assign this issue to you**

### Illustration

- [x] [Open Stickers](https://craftwork.design/downloads/open-stickers/)
- [x] [Halloween](https://craftwork.design/downloads/halloween/)
- [x] [Draw Free](https://craftwork.design/downloads/draw/)
- [x] [Humpy](https://craftwork.design/downloads/humpy-2/)
- [x] [Error 404](https://craftwork.design/downloads/error-404-illustrations/)
- [x] [Flow Lava](https://craftwork.design/downloads/flow-lava-constructor/)
- [x] [Basil](https://craftwork.design/downloads/basil/)
- [x] [Phonies 2](https://growwwkit.com/illustrations/phonies-2/)
- [x] [Tech Peeps](https://growwwkit.com/illustrations/tech-peeps/)
- [x] [Handsome Hands](https://growwwkit.com/illustrations/handsome-hands/)
- [x] [Circuit](https://growwwkit.com/illustrations/circuit/)
- [x] [Chubbs](https://growwwkit.com/illustrations/chubbs/)
- [x] [Metrorama](https://growwwkit.com/illustrations/metrorama/)
- [x] [Familiar Bunch](https://growwwkit.com/illustrations/the-familiar-bunch-illustration-pack/)
- [x] [Sleekbundle](https://sleekbundle.com/)

**Comment by kera-cudmore** [comment]
Afternoon @Anmol-Baranwal would be happy to work on this issue :)
