### ISSUE TITLE
Hacktoberfest : Add illustrations (TODO)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#16]
I am opening this issue for someone looking to contribute, as per [Hacktoberfest](https://hacktoberfest.com/) event.

Open a PR including changes to all the below TODO List of Resources, and make sure to link the issue to the PR so that I get notified that this contribution is done for Hacktoberfest.

Adding the whole list will definitely prove that the contribution is up to the standards of the Hacktoberfest event. 

- **Comment, if you want me to assign this issue to you**

### Illustration

- [x] [AVATARZ](https://www.avatarz.design/)
- [x] [ICONZ 2](https://iconz.design/)
- [x] [Vera Block for Sketch App](https://kkuistore.gumroad.com/l/eeyyU)
- [x] [Mental Health & Psychology](https://drawkit.com/product/mental-health-psychology-illustrations)
- [x] [Landscape & Scenery](https://drawkit.com/product/landscape-scenery-illustrations)
- [x] [Digital Marketing](https://drawkit.com/product/digital-marketing-illustrations)
- [x] [Economy & Finance](https://drawkit.com/product/economy-finance-illustrations)
- [x] [3D Black Friday Mini Icons](https://drawkit.com/product/3d-black-friday-mini-icons)
- [x] [Health & Medical](https://drawkit.com/product/health-medical-illustrations)
- [x] [Christmas & Thanksgiving](https://drawkit.com/product/christmas-thanksgiving-illustrations)
- [x] [Black Friday & Online Shopping](https://drawkit.com/product/black-friday-online-shopping-illustrations)
- [x] [Food & Culture](https://drawkit.com/product/food-culture-illustrations)
- [x] [Love & Family](https://drawkit.com/product/love-family-illustrations)
- [x] [Frosted Glass Computer Icons](https://drawkit.com/product/frosted-glass-computer-icons)
- [x] [Playful Avatar Creator](https://drawkit.com/product/playful-avatar-creator)

**Comment by jpacsai** [comment]
I would like to work on this issue, plz assign it ot me :)

**Comment by jpacsai** [comment]
@Anmol-Baranwal links for the first 3 are mixed up/not correct, perhaps you may want to have a look at them

[AVATARZ](https://iconz.design/)
 [ICONZ 2](https://www.pixsellz.io/mobile-apps-library)
 [Vera Block for Sketch App](https://kkuistore.gumroad.com/l/eeyyU)

**Comment by Anmol-Baranwal** [comment]
@jpacsai  
Thanks for informing me. The links of the first two illustration tasks were not correct.

**Comment by jpacsai** [comment]
@Anmol-Baranwal I was too eager I guess and finished this task too :) Tried to take better pics following your lead and opened a PR already

**Comment by Anmol-Baranwal** [comment]
Completed this issue with [this commit](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/commit/59f80cdbcaea8dcaecd2d12b4fa1f60f693fad0d)
