### ISSUE TITLE
Hacktoberfest : Add illustrations (TODO)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#17]
I am opening this issue for someone looking to contribute, as per [Hacktoberfest](https://hacktoberfest.com/) event.

Open a PR including changes to all the below TODO List of Resources, and make sure to link the issue to the PR so that I get notified that this contribution is done for Hacktoberfest.

Adding the whole list will definitely prove that the contribution is up to the standards of the Hacktoberfest event. 

- **Comment, if you want me to assign this issue to you**

### Illustration

- [x] [Scratches](https://craftwork.design/downloads/scratches/)
- [x] [Tiny Dribbble Shots Constructor](https://craftwork.design/downloads/tiny-dribbble-shots-constructor/)
- [x] [Desk Dudes](https://growwwkit.com/illustrations/desk-dudes/)
- [x] [The Townies](https://growwwkit.com/illustrations/the-townies/)
- [x] [Lil Helpers](https://growwwkit.com/illustrations/lil-helpers/)
- [x] [The Carltons](https://growwwkit.com/illustrations/the-carltons/)
- [x] [Neighbour Larry](https://growwwkit.com/illustrations/neighbour-larry/)
- [x] [Jane](https://growwwkit.com/illustrations/jane/)
- [x] [Springtale](https://growwwkit.com/illustrations/springtale/)
- [x] [Office Dave](https://growwwkit.com/illustrations/office-dave/)
- [x] [Workaholics](https://growwwkit.com/illustrations/workaholics/)
- [x] [Isotopia](https://growwwkit.com/illustrations/isotopia/)
- [x] [Polydrome](https://growwwkit.com/illustrations/polydrome/)
- [x] [Aventine](https://growwwkit.com/illustrations/aventine/)
- [x] [Fundango](https://growwwkit.com/illustrations/fundango/)

**Comment by jpacsai** [comment]
Hi :) I would like to work on this issue, please assign it to me. Thanks!

**Comment by Anmol-Baranwal** [comment]
@jpacsai 
Please, do not reference the issue in the individual commits. 

Since that would be appropriate when the fork is deleted, and it also makes the issue quite a mess.
