### ISSUE TITLE
Hacktoberfest : Add illustrations (TODO)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#18]
I am opening this issue for someone looking to contribute, as per [Hacktoberfest](https://hacktoberfest.com/) event.

Open a PR including changes to all the below TODO List of Resources, and make sure to link the issue to the PR so that I get notified that this contribution is done for Hacktoberfest.

Adding the whole list will definitely prove that the contribution is up to the standards of the Hacktoberfest event. 

- **Comment, if you want me to assign this issue to you**

### Illustration

- [x] [EMOJIZ](https://emojiz.design/)
- [x] [ANIMALZ](https://animalz.design/)
- [x] [AVATARZ](https://www.avatarz.design/)
- [x] [Nutrition Icons](https://drawkit.com/product/nutrition-icons)
- [x] [Mental Health Icons](https://drawkit.com/product/mental-health-icons)
- [x] [Website States Icons](https://drawkit.com/product/website-states-icons)
- [x] [Education Icons](https://drawkit.com/product/free-education-icons)
- [x] [Ecology & Nature Icons](https://drawkit.com/product/ecology-nature-free-icons)
- [x] [Startups and SaaS Icons](https://drawkit.com/product/startups-and-saas-icons)
- [x] [COVID-19 Icons](https://drawkit.com/product/covid-19)
- [x] [Food & Drink Icons](https://drawkit.com/product/food-drink)
- [x] [Ugly Delicious](https://drawer.design/products/ugly-delicious/)
- [x] [Social Work & Charity](https://drawkit.com/product/social-work-charity-illustrations)
- [x] [COVID-19 & Vaccinations](https://drawkit.com/product/covid-19-vaccinations)
- [x] [Product & Project Managers](https://drawkit.com/product/project-product-manager-illustrations)

**Comment by jpacsai** [comment]
I would like to work on this issue, please assign it to me. Thanks!

**Comment by Anmol-Baranwal** [comment]
@jpacsai  
Hold on, and don't make a PR of this issue till the previous PR of yours is merged. I will request some changes in a few minutes.

**Comment by jpacsai** [comment]
ok, sure, no problem.

**Comment by jpacsai** [comment]
@Anmol-Baranwal I start work on this issue as my previous PR has been merged

**Comment by Anmol-Baranwal** [comment]
Yeah, go ahead.

**Comment by Anmol-Baranwal** [comment]
@jpacsai 
Please, do not reference the issue in the individual commits.

Since that would be appropriate when the fork is deleted, and it also makes the issue quite a mess.
