### ISSUE TITLE
Hacktoberfest : Add illustrations (TODO)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Anmol-Baranwal/Awesome-Illustrations-4Projects#19]
I am opening this issue for someone looking to contribute, as per [Hacktoberfest](https://hacktoberfest.com/) event.

Open a PR including changes to all the below TODO List of Resources, and make sure to link the issue to the PR so that I get notified that this contribution is done for Hacktoberfest.

Adding the whole list will definitely prove that the contribution is up to the standards of the Hacktoberfest event. 

- **Comment, if you want me to assign this issue to you**

### Illustration

- [x] [Social Media Icons](https://drawkit.com/product/3d-social-media-icons)
- [ ] [Working From Home](https://drawkit.com/product/working-from-home-illustrations)
- [ ] [E-commerce Illustrations & Icons Kit](https://drawkit.com/product/online-shopping-and-ecommerce-illustrations-icons)
- [ ] [Peach Illustration System](https://drawkit.com/product/peach-illustration-system)
- [x] [Watermelon Illustrations](https://drawkit.com/product/watermelon-illustrations)
- [ ] [Laboratorium](https://growwwkit.com/illustrations/laboratorium/)
- [ ] [Dreamwork](https://growwwkit.com/illustrations/dreamwork/)
- [ ] [Lubo](https://growwwkit.com/illustrations/lubo/)
- [ ] [Streamlinehq](https://www.streamlinehq.com/)
- [ ] [Coronavirus Icons](https://drawer.design/products/coronavirus-icons/)
- [ ] [FreeIllustrations](https://freeillustrations.xyz/)
- [x] [Essential eCommerce Icons](https://drawer.design/products/essential-e-commerce-icons/)
- [x] [Mary Animated Illustrations](https://drawer.design/products/mary-animated-illustrations/)
- [x] [Distance Learning](https://drawer.design/products/distance-learning/)
- [ ] [Smartsharp](https://craftwork.design/downloads/smartsharp-illustrations/)

**Comment by Rositasikarwar** [comment]
I would like to work on this issue, please assign it to me. Thanks!

**Comment by Rositasikarwar** [comment]
Thanks🤝

**Comment by Anmol-Baranwal** [comment]
@Rositasikarwar 
May I know, till when are you planning to complete this issue?
